version: '3.8'
networks:
  routing:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
services:
  traefik:
    image: traefik:2.11.0
    restart: always
    container_name: reverse_proxy_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/certs:ro
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    networks:
      routing:
        ipv4_address: 10.100.100.10
