## static configuration

global:
  # Send anonymous usage data
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Access logs
# accessLog: fields:
#   headers:
#     names:
#       User-Agent: keep

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      tlschallenge: true
      httpchallenge:
        entrypoint: web
      email: mail@somedomain.com
      storage: /etc/traefik/acme/acme.json

api:
  dashboard: true

log:
  level: ERROR
